#pragma once

//Game
#define COUNTDOWN_START 1
#define COUNTDOWN_NEXT_LEVEL 2
#define LEVEL_COUNT 3

#define MAX_SIMULTANEOUS_COLLISIONS 8

//Player
#define INITIAL_HEALTH_COUNT 4
#define MAX_HEALTH_COUNT 6
#define MAX_BULLET_COUNT 10
#define POINTS_FOR_HEALTH 10000
#define IMMUNITY_PERIODE 1000


// Physics
#define SHIP_MAX_SPEED 2.3
#define SHIP_DRAG_AMOUNT 0.01
#define SHIP_CONTROL_SPEED_MULTIPLIER 0.7

//Multiplayer

//Asteroids
#define MAX_ASTEROID_COUNT_GAME 11
#define MAX_ASTEROID_COUNT_MP 6
#define ADD_ASTEROID_PER_LEVEL 2
#define INITIAL_ASTEROID_COUNT 5
#define RADIUS_BIG_ASTEROID 20
#define RADIUS_SMALL_ASTEROID 10
#define RADIUS_COLLIDER 25
#define POINTS_DESTROY_BIG_ASTEROID 250
#define POINTS_DESTROY_SMALL_ASTEROID 500
#define POINTS_DESTROY_UFO 1000

//UFO
#define UFO_SPAWN_MIN_SCORE 2000
#define UFO_MAX_LIFES_MP 4
#define UFO_MAX_LIFES_SP 3
#define UFO_MAX_COUNT 2
#define UFO_MAX_COUNT_MENU 3

//Design 
#define LEFT_TEXT_MARGIN 30

//SOUND
#define GAME_SOUND_LEVEL 30
#define GAME_MUSIC_LEVEL 40

//MODES
#define GAME_MODE_SP 0
#define GAME_MODE_MP 1
#define GAME_MODE_GOD 2 //God Like
