#pragma once

//Game
#define COUNTDOWN_START 1

//Player
#define INITIAL_HEALTH_COUNT 4
#define MAX_HEALTH_COUNT 6
#define MAX_BULLET_COUNT 10
#define POINTS_FOR_HEALTH 5000

//Asteroids
#define MAX_ASTEROID_COUNT_GAME 10
#define INITIAL_ASTEROID_COUNT 5
#define RADIUS_BIG_ASTEROID 20
#define RADIUS_SMALL_ASTEROID 10
#define RADIUS_COLLIDER 25

#define POINTS_DESTROY_BIG_ASTEROID 250
#define POINTS_DESTROY_SMALL_ASTEROID 500
#define POINTS_DESTROY_UFO 1000



