#pragma once

//Game
#define COUNTDOWN_START 1
#define COUNTDOWN_NEXT_LEVEL 2
#define LEVEL_COUNT 3

//Player
#define INITIAL_HEALTH_COUNT 4
#define MAX_HEALTH_COUNT 6
#define MAX_BULLET_COUNT 10
#define POINTS_FOR_HEALTH 5000

//Multiplayer

//Asteroids
#define MAX_ASTEROID_COUNT_GAME 15
#define ADD_ASTEROID_PER_LEVEL 2
#define INITIAL_ASTEROID_COUNT 5
#define RADIUS_BIG_ASTEROID 20
#define RADIUS_SMALL_ASTEROID 10
#define RADIUS_COLLIDER 25
#define POINTS_DESTROY_BIG_ASTEROID 250
#define POINTS_DESTROY_SMALL_ASTEROID 500
#define POINTS_DESTROY_UFO 1000

//UFO
#define UFO_MAX_LIFES 10

//SOUND
#define GAME_SOUND_LEVEL 30
#define GAME_MUSIC_LEVEL 40

